---
title: "README"
author: "Marco Cazzola"
date: "8/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### **Brief app description**

Given a csv file collecting the results of a certain football championship, this app allows you to choose a certain team and set a day range, according to which you can see the statistics of the selected team in the selected day range for what concerns the following three categories: 

- *Wins/Draws/Losses*: let you visualize how many matches the selected team has won, lost or drawn in the selected period.

- *Even vs Odd*: let you visualize how many matches played by the selected team in the selected period had an even or odd total number of goals.

- *Matches with at least 3 goals*: let you visualize how many matches played by the team in the selected period had less than or at least 3 total goals. 

The distribution of the matches will be visualized as a bar plot. The pre-selected dates are the earliest and the latest one in the selected CSV. 

### **Data**

The data used for this app come from the site <https://www.football-data.co.uk/data.php>. 

There you can find csv files for several championship; in the `data` folder of the app you can already find the following files: 

- `D1`: data about the 2020-21 German championship, updated to 04-07-2021

- `E1`: data about the 2020-21 English championship, updated to 04-07-2021

- `F1`: data about the 2020-21 French championship, updated to 04-05-2021

- `I1`: data about the 2020-21 Italian championship, updated to 04-07-2021

- `S1`: data about the 2020-21 Spanish championship, updated to 04-07-2021

**IMPORTANT**: notice that the app is very flexible; in order to change the championship and/or the season, you just need to change the file updated in the sixth line of the app. So you can download files about other seasons and/or other championships from the site mentioned above and let the app analyze them for you. 

The csv files contain more than 100 columns, however the ones of our interest that will be selected by the app are just these six: 

- `Date`: match date

- `HomeTeam`: Home Team, i.e. the team which is hosting the match

- `AwayTeam`: Away Team, i.e. the opponent team

- `FTHG`: Full Time Home Team Goals, i.e. the number of goals scored by the Home Team

- `FTAG`: Full Time Away Team Goals, i.e. the number of goals scored by the Away Team

- `FTR`: Full Time Result, i.e. the match's final result. More specifically: 
    - `H` means Home Team won
    - `A` means Away Team won
    - `D` means there was a draw

More details about the data collected in the file can be found at <https://www.football-data.co.uk/notes.txt>. 

To run the app on your device, just run the following commands: 

library(shiny)
runGitHub("Football-stats", "marcocazzola", ref="main")
